// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHQQJfrhG0E5VrVaR_Sw6npzTfGBU8gI4',
    appId: '1:1027479018342:web:6f3c3c22eb6325b94246a7',
    messagingSenderId: '1027479018342',
    projectId: 'nazwa-tubesppb',
    authDomain: 'nazwa-tubesppb.firebaseapp.com',
    storageBucket: 'nazwa-tubesppb.appspot.com',
    measurementId: 'G-79K96RLGFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ln6v51ptRtczce-PWVko2BSxMKQRKU4',
    appId: '1:1027479018342:android:d8188e5fe4bb52444246a7',
    messagingSenderId: '1027479018342',
    projectId: 'nazwa-tubesppb',
    storageBucket: 'nazwa-tubesppb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_kgNRukhhmEl-SbzeVkBC8KXcTnHh1UY',
    appId: '1:1027479018342:ios:3fbb731d3ff9c4c14246a7',
    messagingSenderId: '1027479018342',
    projectId: 'nazwa-tubesppb',
    storageBucket: 'nazwa-tubesppb.appspot.com',
    iosBundleId: 'com.example.nazwaTiketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_kgNRukhhmEl-SbzeVkBC8KXcTnHh1UY',
    appId: '1:1027479018342:ios:3fbb731d3ff9c4c14246a7',
    messagingSenderId: '1027479018342',
    projectId: 'nazwa-tubesppb',
    storageBucket: 'nazwa-tubesppb.appspot.com',
    iosBundleId: 'com.example.nazwaTiketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHQQJfrhG0E5VrVaR_Sw6npzTfGBU8gI4',
    appId: '1:1027479018342:web:5ae6d7cb78573d904246a7',
    messagingSenderId: '1027479018342',
    projectId: 'nazwa-tubesppb',
    authDomain: 'nazwa-tubesppb.firebaseapp.com',
    storageBucket: 'nazwa-tubesppb.appspot.com',
    measurementId: 'G-DSV3XP3H5R',
  );
}
