// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpa-ew7UedfP4x80Ee3yt0g4f7sMsFRi8',
    appId: '1:497104196815:web:50bdcbacbdabf1b48493ba',
    messagingSenderId: '497104196815',
    projectId: 'tubesppb-c0236',
    authDomain: 'tubesppb-c0236.firebaseapp.com',
    storageBucket: 'tubesppb-c0236.appspot.com',
    measurementId: 'G-E2R1L1GV0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIliuGCZQrArieGgroT-ww6UX1VkN4q8',
    appId: '1:497104196815:android:086f9b7826d0035c8493ba',
    messagingSenderId: '497104196815',
    projectId: 'tubesppb-c0236',
    storageBucket: 'tubesppb-c0236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Zlv9XbsqKiqiRYBj9kMA3tX6U2dcsls',
    appId: '1:497104196815:ios:919d1276acc2a5958493ba',
    messagingSenderId: '497104196815',
    projectId: 'tubesppb-c0236',
    storageBucket: 'tubesppb-c0236.appspot.com',
    iosClientId: '497104196815-82gbdur5h1bkgfhdrl11hsvt4sdr97u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nazwaTiketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Zlv9XbsqKiqiRYBj9kMA3tX6U2dcsls',
    appId: '1:497104196815:ios:919d1276acc2a5958493ba',
    messagingSenderId: '497104196815',
    projectId: 'tubesppb-c0236',
    storageBucket: 'tubesppb-c0236.appspot.com',
    iosClientId: '497104196815-82gbdur5h1bkgfhdrl11hsvt4sdr97u8.apps.googleusercontent.com',
    iosBundleId: 'com.example.nazwaTiketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpa-ew7UedfP4x80Ee3yt0g4f7sMsFRi8',
    appId: '1:497104196815:web:8ab72a0fa94ef9478493ba',
    messagingSenderId: '497104196815',
    projectId: 'tubesppb-c0236',
    authDomain: 'tubesppb-c0236.firebaseapp.com',
    storageBucket: 'tubesppb-c0236.appspot.com',
    measurementId: 'G-8T88PKQVHE',
  );

}